### ISSUE TITLE
Problem to make install for bayeux

### ISSUE THREAD

**Issue by miroslav-macko** [SuperNEMO-DBD/homebrew-cadfael#12]
### Bug reports:

Hello!

I am trying to brew falaise and I managed to get rid of some problems up to some point when I am totally without any clue what might help.
All the dependencies of falaise were installed until make install step for bayeux.
Here is output I got:

[macko@borcluster1 Formula]$ brew install falaise
==> Installing falaise from supernemo-dbd/cadfael
==> Installing dependencies for supernemo-dbd/cadfael/falaise: supernemo-dbd/cadfael/bayeux
==> Installing supernemo-dbd/cadfael/falaise dependency: supernemo-dbd/cadfael/bayeux
==> Downloading https://files.warwick.ac.uk/supernemo/files/Cadfael/distfiles/Bayeux-2.1.0.tar.gz
Already downloaded: /home/macko/.cache/Homebrew/bayeux-2.1.0.tar.gz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/home/macko/Softver/linuxbrew/Cellar/bayeux/2.1.0_2 -
==> make install
Last 15 lines from /home/macko/.cache/Homebrew/Logs/bayeux/02.make:
                 from /home/macko/Softver/linuxbrew/include/boost/iostreams/detail/push.hpp:24,
                 from /home/macko/Softver/linuxbrew/include/boost/iostreams/filtering_stream.hpp:19,
etc....

I am also attaching file /home/macko/.cache/Homebrew/Logs/bayeux/02.make
[02.make.txt](https://github.com/SuperNEMO-DBD/homebrew-cadfael/files/861359/02.make.txt)

The problem seems to be in this part:

#error "You need a ISO C conforming compiler to use the glibc headers"

I tried to google what might be the problem but it was not very helpful for me.

I hope you can help somehow.

Thank you,

Miroslav Macko

**output of brew config:**

[macko@borcluster1 ~]$ brew config
HOMEBREW_VERSION: 1.1.10-34-g92bb61c50
ORIGIN: https://github.com/Linuxbrew/brew.git
HEAD: 92bb61c506afd09388af2a391dd3f5998bdd4404
Last commit: 12 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: acb11f825ac0b49d3b5420a2f7e90cf67e9bf440
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /home/macko/Softver/linuxbrew
HOMEBREW_REPOSITORY: /home/macko/Softver/linuxbrew
HOMEBREW_CELLAR: /home/macko/Softver/linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: 24-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648 => /home/macko/Softver/linuxbrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
Clang: N/A
Git: 2.12.0 => /home/macko/Softver/linuxbrew/bin/git
Perl: /usr/bin/perl
Python: /home/macko/Softver/linuxbrew/bin/python => /home/macko/Softver/linuxbrew/Cellar/python/2.7.13/bin/python2.7
Ruby: /usr/bin/ruby
Java: 1.6.0_39
Kernel: Linux 2.6.32-573.26.1.el6.x86_64 x86_64 GNU/Linux
OS: Scientific Linux release 6.4 (Carbon)
Codename: Carbon
OS glibc: 2.12
OS gcc: 4.4.7
Linuxbrew glibc: 2.19
Linuxbrew gcc: 5.3.0
Linuxbrew xorg: N/A

**output of brew doctor:**

[macko@borcluster1 Formula]$ brew doctor
Your system is ready to brew.

**Comment by drbenmorgan** [comment]
I'd suspect this is down to using Linuxbrew's gcc and glibc. These aren't supported yet (I'll update the documents to reflect this), so the only solution is to remove your existing brew install (or create a new one) and do:

```console
# ... Ensure you have don't have PATH or LD_LIBRARY_PATH pointing to any other locations...
$ git clone https://github.com/SuperNEMO-DBD/brew.git cadfaelbrew
$ cd cadfaelbrew
$ ./bin/brew cadfael-bootstrap
$ ./bin/brew install falaise
```

**Comment by miroslav-macko** [comment]
I tried to install this way and I got this message:

==> Checking for install of rpm 'openssl-devel': openssl-devel-1.0.1e-42.el6_7.4
Error: RPM 'ruby-irb.x86_64' is not installed
Error: RPM 'HEP_OSlibs_SL6' is not installed
Error: Yum Group 'Development tools' is not installed
Error: RPMs 'HEP_OSlibs_SL6 ruby-irb.x86_64 ' are not installed on this system
Error: Please run (or get your sysadmin to run):

  <unknown:packagemanager> install HEP_OSlibs_SL6 ruby-irb.x86_64 

Error: Yum Groups ''Development tools'' are not installed on this system
Error: Please run (or get your sysadmin to run):

  yum groupinstall 'Development tools'

Error: System software check failed

I am working in cluster system I cannot get sudo access to. Is there possiblity to install those 'Development tools' without sudo access? Maybe it is trivial issue but I was not able to do that. Thanks for any help.

**Comment by drbenmorgan** [comment]
As it says in the error message, contact support for your cluster and ask for the installation of the listed packages and groups. So for the base packages:

```
$ yum install ruby-irb.x86_64
$ yum groupinstall 'Development tools'
```

`HEP_OSlibs` is supplied by CERN, and there are instructions at https://twiki.cern.ch/twiki/bin/view/LCG/SL6DependencyRPM for installing this via the CERN repository and associated GPG key.

**Comment by drbenmorgan** [comment]
Closing issues more than 2 months old with no update, please reopen if required.
