### ISSUE TITLE
flsimulate can't find Bayeux library

### ISSUE THREAD

**Issue by cherylepatrick** [SuperNEMO-DBD/homebrew-cadfael#14]
I've installed Falaise/Bayeux 3.0 (on MacOSX Sierra) and I think it was successful. However flsimulate can't find the Bayeux library:
dyld: Library not loaded: @rpath/libBayeux.3.dylib
  Referenced from: /Users/cpatrick/CadfaelBrew/bin/flsimulate
  Reason: image not found
Abort trap: 6

That library exists but is in /Users/cpatrick/CadfaelBrew/lib rather than bin. Do I need to set up some environment variable or something to tell it to look there? I cleared out my LD_LIBRARY_PATH and DYLD_LIBRARY_PATH (which pointed to the root5 directories for reasons I no longer recall), but it made no difference.
Thanks in advance for suggestions!

**Comment by drbenmorgan** [comment]
Could you try running 

```
$ brew log -n5
```

and

```
$ brew config
```

and post the output here please? This looks like an error that should have been resolved by a commit in the main brew repository.

**Comment by cherylepatrick** [comment]
eduroam-int-dhcp-97-252-40:~ cpatrick$ brew log -n5
Warning: The git repository is a shallow clone therefore the filtering may be incorrect.
Use `git fetch --unshallow` to get the full repository.
commit 59c9ddbc1d9b9dfdeb0514768e0efd0112c63b25
Author: Shaun Jackman <sjackman@gmail.com>
Date:   Fri Mar 31 12:07:19 2017 -0700

    Use --env=super by default for Linuxbrew

commit ff96869a878aa723a40fff553a6c51158baa982f
Author: Shaun Jackman <sjackman@gmail.com>
Date:   Fri Mar 31 12:06:20 2017 -0700

    Revert "Add env :super for Linuxbrew (#270)"
    
    This reverts commit 09b6b09247ba0b21f81116e812d109818b634c6c.

commit 609d5e7524ba334a5b469825a068710d98d6a37b
Author: Shaun Jackman <sjackman@gmail.com>
Date:   Sat Apr 8 09:14:04 2017 -0700

    linkage: Add to the host white list for Linuxbrew
    
    Add libcrypt.so.1 libnsl.so.1 libutil.so.1

commit bb231cb3d0fa1b341a6f48210400106b7aff503a
Author: Shaun Jackman <sjackman@gmail.com>
Date:   Thu Apr 6 22:20:57 2017 -0700

    Use unzip not homebrew/dupes/unzip for Linuxbrew (#330)

commit 3f4726e2374ba938aa3973d8ca5ff052056df876
Author: Shaun Jackman <sjackman@gmail.com>
Date:   Thu Apr 6 15:41:03 2017 -0700

    linkage: Expand the host whitelist for Linuxbrew
eduroam-int-dhcp-97-252-40:~ cpatrick$ brew config
HOMEBREW_VERSION: 1.1.11
ORIGIN: https://github.com/SuperNEMO-DBD/brew.git
HEAD: 59c9ddbc1d9b9dfdeb0514768e0efd0112c63b25
Last commit: 4 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 12f5aebe20d2a2916b43da2d3c43c6a665f680f3
Core tap last commit: 22 hours ago
HOMEBREW_PREFIX: /Users/cpatrick/CadfaelBrew
HOMEBREW_REPOSITORY: /Users/cpatrick/CadfaelBrew
HOMEBREW_CELLAR: /Users/cpatrick/CadfaelBrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /Users/cpatrick/CadfaelBrew/bin/python => /Users/cpatrick/CadfaelBrew/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.4-x86_64
Xcode: 8.3.2
CLT: 8.3.2.0.1.1492020469
X11: 2.7.11 => /opt/X11

**Comment by cherylepatrick** [comment]
Also I ran brew update:
eduroam-int-dhcp-97-252-40:~ cpatrick$ brew update
Updated 1 tap (homebrew/core).
==> Updated Formulae
arangodb         gnome-recipes    macvim           svtplay-dl       yaz
at-spi2-atk      immortal         make             tcpreplay
at-spi2-core     influxdb         opencore-amr     tippecanoe
convox           kobalt           pwntools         vault
fabio            libsoup          serveit          vice

**Comment by drbenmorgan** [comment]
O.k., just to double check, could you run

```
$ git -C $(brew --prefix) fetch --unshallow
```

and run the `brew log -n5` command again please? Also, what's the output of 

```
$ git -C $(brew --prefix) remote -v
```

What the config output is showing is that brew appears to be on a tag version, and you have commits that aren't in SuperNEMO's brew.

**Comment by cherylepatrick** [comment]
eduroam-int-dhcp-97-252-40:~ cpatrick$ git -C $(brew --prefix) fetch --unshallow
remote: Counting objects: 32, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 32 (delta 23), reused 31 (delta 22), pack-reused 0
Unpacking objects: 100% (32/32), done.
eduroam-int-dhcp-97-252-40:~ cpatrick$ brew log -n5
commit 59c9ddbc1d9b9dfdeb0514768e0efd0112c63b25
Author: Shaun Jackman <sjackman@gmail.com>
Date:   Fri Mar 31 12:07:19 2017 -0700

    Use --env=super by default for Linuxbrew

commit ff96869a878aa723a40fff553a6c51158baa982f
Author: Shaun Jackman <sjackman@gmail.com>
Date:   Fri Mar 31 12:06:20 2017 -0700

    Revert "Add env :super for Linuxbrew (#270)"
    
    This reverts commit 09b6b09247ba0b21f81116e812d109818b634c6c.

commit 609d5e7524ba334a5b469825a068710d98d6a37b
Author: Shaun Jackman <sjackman@gmail.com>
Date:   Sat Apr 8 09:14:04 2017 -0700

    linkage: Add to the host white list for Linuxbrew
    
    Add libcrypt.so.1 libnsl.so.1 libutil.so.1

commit bb231cb3d0fa1b341a6f48210400106b7aff503a
Author: Shaun Jackman <sjackman@gmail.com>
Date:   Thu Apr 6 22:20:57 2017 -0700

    Use unzip not homebrew/dupes/unzip for Linuxbrew (#330)

commit 3f4726e2374ba938aa3973d8ca5ff052056df876
Author: Shaun Jackman <sjackman@gmail.com>
Date:   Thu Apr 6 15:41:03 2017 -0700

    linkage: Expand the host whitelist for Linuxbrew
eduroam-int-dhcp-97-252-40:~ cpatrick$ git -C $(brew --prefix) remote -v
Linuxbrew	https://github.com/Linuxbrew/brew.git (fetch)
Linuxbrew	https://github.com/Linuxbrew/brew.git (push)
origin	https://github.com/SuperNEMO-DBD/brew.git (fetch)
origin	https://github.com/SuperNEMO-DBD/brew.git (push)

I wonder if I did something odd with this in the past and checked out a weird version, and now it is coming back to bite me?

**Comment by drbenmorgan** [comment]
I think that's the case, I'm not sure why the "Linuxbrew" remote would be there (it's just possible there's a bug, but I think testing would have picked that up). What I'd suggest is:

1. Do `git -C $(brew --prefix) remote rm Linuxbrew`
2. Try `git -C $(brew --prefix) fetch origin`
3. If that works, `git -C $(brew --prefix) reset --hard 161e0bcdf`

This should get you back to the head of SuperNEMO's brew. If the above work without error, then you can try:

```
$ brew update
$ brew rm bayeux falaise root5
$ brew install falaise
```

It's likely that additional formulae will need to be reinstalled, but let's try the above first.

**Comment by cherylepatrick** [comment]
Thanks for the help. I did all you suggested, but "brew install falaise" claimed falaise was already installed (even though I had just done the brew rm line). (It also said root5 was not installed when I tried to do the rm, but that is true, I uninstalled it earlier to stop myself getting error messages when I tried to run root 6). Do I need to brew uninstall falaise and bayeux too?

**Comment by drbenmorgan** [comment]
Ah, sorry, it's probably only uninstalled falaise/bayeux 3, so try

```
$ brew rm --force bayeux falaise root5
```

That should remove any and all versions, so should then allow the re-install of falaise.

**Comment by cherylepatrick** [comment]
Cool, now it is installing, wish me luck!

**Comment by cherylepatrick** [comment]
It ran suspiciously quickly, and now flsimulate is giving 
dyld: Library not loaded: @rpath/libCore.6.08.so
  Referenced from: /Users/cpatrick/CadfaelBrew/bin/flsimulate
  Reason: image not found
Is that a sign of something else that needs a reinstall too?

**Comment by cherylepatrick** [comment]
Oh wait, that is a root library, maybe this is a problem with my LD_LIBRARY_PATH

**Comment by drbenmorgan** [comment]
Right, it looks like the issue has filtered through to other packages. I'd suggest doing:

```
$ brew reinstall root6 boost bayeux falaise
```

It is probably those that have caused the issue (I think geant4 will be o.k. as it hasn't been upgraded).

**Comment by cherylepatrick** [comment]
I tried all of those and it didn't work... now I get
dyld: Library not loaded: @rpath/QtSvg.framework/Versions/5/QtSvg
  Referenced from: /Users/cpatrick/CadfaelBrew/bin/flsimulate
  Reason: image not found
Abort trap: 6
I figured maybe that was QT so I reinstalled that as well. It took hours and made no difference. Any other suggestions? Sorry about this!

**Comment by drbenmorgan** [comment]
Don't apologise - good to get feedback!

I think, unfortunately, this means the whole stack is going to be affected, so I would recommend doing:

```
$ brew rm --force $(brew ls)
$ brew cadfael-bootstrap
$ brew install falaise
```

That's a complete rebuild, but think it's going to be needed...

**Comment by cherylepatrick** [comment]
Well it was drastic, but it seems like it worked. Yay! Thanks for your help, Ben!
