### ISSUE TITLE
Minor issue during first setup

### ISSUE THREAD

**Issue by cascella** [SuperNEMO-DBD/homebrew-cadfael#16]
run the commands suggested on the homepage with a new user account:
$ git clone https://github.com/SuperNEMO-DBD/brew.git cadfaelbrew
$ cd cadfaelbrew
$ ./bin/brew cadfael-bootstrap

the last command fails with:
==> Using the sandbox
Error: Operation not permitted - /Users/cadfael/.cache
Error: Failed to bootstrap cadfael toolchain

This is easily fixed with
$ mkdir  /Users/cadfael/.cache

I think the directory should be created automatically if it's not there.

**Comment by drbenmorgan** [comment]
Closing issues with no update in 2 months - please reopen if the issue is not resolved.
