### ISSUE TITLE
PTD2root won't install on OSX or Linux

### ISSUE THREAD

**Issue by cherylepatrick** [SuperNEMO-DBD/homebrew-cadfael#17]
No luck with  `brew install ptd2root` on either SL6 or OSX Sierra. Error message text differs but in both cases it can't find TFile.h. Both systems will run root OK, and get root 6. Am I missing something in an environment variable?

- [ x] Ran `brew update` and retried your prior step?
- [ x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ x] Confirmed this is a problem with specific formulae and not brew? If it's a general brew problem please file this issue at https://github.com/supernemo-dbd/brew/issues/new

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:
`[cpatrick@pc133 testfalaise3]$ brew config
HOMEBREW_VERSION: >1.1.0 (no git repository)
ORIGIN: https://github.com/SuperNEMO-DBD/brew.git
HEAD: 161e0bcdf81098f678ff177e66f813f464d3f830
Last commit: 6 weeks ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: e2ae7ffdc4898a0c2797dd31c05a67840d6509ae
Core tap last commit: 20 hours ago
HOMEBREW_PREFIX: /unix/nemo2/users/cpatrick/CadfaelBrew
HOMEBREW_REPOSITORY: /unix/nemo2/users/cpatrick/CadfaelBrew
HOMEBREW_CELLAR: /unix/nemo2/users/cpatrick/CadfaelBrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: dual-core 64-bit 0xf43
Homebrew Ruby: 2.0.0-p648 => /unix/nemo2/users/cpatrick/CadfaelBrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
Clang: N/A
Git: 2.13.0 => /unix/nemo2/users/cpatrick/CadfaelBrew/bin/git
Perl: /usr/bin/perl
Python: /unix/nemo2/users/cpatrick/CadfaelBrew/bin/python => /unix/nemo2/users/cpatrick/CadfaelBrew/Cellar/python/2.7.13/bin/python2.7
Ruby: /unix/nemo2/users/cpatrick/CadfaelBrew/bin/ruby => /unix/nemo2/users/cpatrick/CadfaelBrew/Cellar/ruby/2.4.1_1/bin/ruby
Java: 1.7.0_141
Kernel: Linux 2.6.32-696.el6.x86_64 x86_64 GNU/Linux
OS: Scientific Linux release 6.9 (Carbon)
Codename: Carbon
OS glibc: 2.12
OS gcc: 4.4.7
Linuxbrew glibc: N/A
Linuxbrew gcc: N/A
Linuxbrew xorg: N/A
`
`[cpatrick@pc133 testfalaise3]$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/log_event.h
  /usr/local/include/trq_auth_daemon.h
  /usr/local/include/pbs_log.h
  /usr/local/include/u_lock_ctl.h
  /usr/local/include/setup_env.h
  /usr/local/include/chk_file_sec.h
  /usr/local/include/lib_net.h
  /usr/local/include/pbsnodes.h
  /usr/local/include/common_cmds.h
  /usr/local/include/attr_node_func.h
  /usr/local/include/lib_ifl.h
  /usr/local/include/lib_utils.h
  /usr/local/include/qsub_functions.h

Warning: You have a curlrc file
If you have trouble downloading packages with Homebrew, then maybe this
is the problem? If the following command doesn't work, then try removing
your curlrc:
  curl https://github.com

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /unix/nemo2/users/cpatrick/CadfaelBrew/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/unix/nemo2/users/cpatrick/CadfaelBrew/sbin:$PATH"' >> ~/.bash_profile`

`[cpatrick@pc133 testfalaise3]$ brew gist-logs ptd2root
https://gist.github.com/6a87db9fa3609e873f0e7d457c26cd71`

**Comment by cherylepatrick** [comment]
`[cpatrick@pc133 testfalaise3]$ brew install ptd2root
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

==> Installing ptd2root from supernemo-dbd/cadfael
Warning: Use unzip instead of deprecated homebrew/dupes/unzip
[Repeat ad nauseum]
==> Downloading https://github.com/SuperNEMO-DBD/PTD2Root/archive/v0.1.0.tar.gz
Already downloaded: /home/cpatrick/.cache/Homebrew/ptd2root-0.1.0.tar.gz
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMA
==> make install
Last 15 lines from /home/cpatrick/.cache/Homebrew/Logs/ptd2root/02.make:
make[2]: Leaving directory `/tmp/ptd2root-20170517-25146-lx7327/PTD2Root-0.1.0'
make -f CMakeFiles/PTD2Root.dir/build.make CMakeFiles/PTD2Root.dir/build
make[2]: Entering directory `/tmp/ptd2root-20170517-25146-lx7327/PTD2Root-0.1.0'
[ 50%] Building CXX object CMakeFiles/PTD2Root.dir/ptd2root.cpp.o
/unix/nemo2/users/cpatrick/CadfaelBrew/bin/g++-4.9  -DPTD2Root_EXPORTS  -Os -w -pipe -march=native -DNDEBUG -fPIC   -o CMakeFiles/PTD2Root.dir/ptd2root.cpp.o -c /tmp/ptd2root-20170517-25146-lx7327/PTD2Root-0.1.0/ptd2root.cpp
In file included from /tmp/ptd2root-20170517-25146-lx7327/PTD2Root-0.1.0/ptd2root.cpp:8:0:
/tmp/ptd2root-20170517-25146-lx7327/PTD2Root-0.1.0/ptd2root.h:13:19: fatal error: TFile.h: No such file or directory
 #include "TFile.h"
                   ^
compilation terminated.
make[2]: *** [CMakeFiles/PTD2Root.dir/ptd2root.cpp.o] Error 1
make[2]: Leaving directory `/tmp/ptd2root-20170517-25146-lx7327/PTD2Root-0.1.0'
make[1]: *** [CMakeFiles/PTD2Root.dir/all] Error 2
make[1]: Leaving directory `/tmp/ptd2root-20170517-25146-lx7327/PTD2Root-0.1.0'
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/supernemo-dbd/homebrew-cadfael/issues

`

**Comment by cherylepatrick** [comment]
That was from the linux box, the error I get on the mac is:
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMA
==> make install
Last 15 lines from /Users/cpatrick/Library/Logs/Homebrew/ptd2root/02.make:
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 all
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/PTD2Root.dir/build.make CMakeFiles/PTD2Root.dir/depend
cd /tmp/ptd2root-20170517-47254-126osij/PTD2Root-0.1.0 && /Users/cpatrick/CadfaelBrew/Cellar/cmake/3.8.1/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/ptd2root-20170517-47254-126osij/PTD2Root-0.1.0 /tmp/ptd2root-20170517-47254-126osij/PTD2Root-0.1.0 /tmp/ptd2root-20170517-47254-126osij/PTD2Root-0.1.0 /tmp/ptd2root-20170517-47254-126osij/PTD2Root-0.1.0 /tmp/ptd2root-20170517-47254-126osij/PTD2Root-0.1.0/CMakeFiles/PTD2Root.dir/DependInfo.cmake --color=
Scanning dependencies of target PTD2Root
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/PTD2Root.dir/build.make CMakeFiles/PTD2Root.dir/build
[ 50%] Building CXX object CMakeFiles/PTD2Root.dir/ptd2root.cpp.o
/Users/cpatrick/CadfaelBrew/Library/Homebrew/shims/super/clang++  -DPTD2Root_EXPORTS  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12 -fPIC   -o CMakeFiles/PTD2Root.dir/ptd2root.cpp.o -c /tmp/ptd2root-20170517-47254-126osij/PTD2Root-0.1.0/ptd2root.cpp
In file included from /tmp/ptd2root-20170517-47254-126osij/PTD2Root-0.1.0/ptd2root.cpp:8:
/tmp/ptd2root-20170517-47254-126osij/PTD2Root-0.1.0/ptd2root.h:13:10: fatal error: 'TFile.h' file not found
#include "TFile.h"
         ^
1 error generated.
make[2]: *** [CMakeFiles/PTD2Root.dir/ptd2root.cpp.o] Error 1
make[1]: *** [CMakeFiles/PTD2Root.dir/all] Error 2
make: *** [all] Error 2

**Comment by drbenmorgan** [comment]
@cherylepatrick PR #20 should address this issue - can you try

```
$ brew update
$ brew install ptd2root
```

again please? It should have at least a version bump to 1.0.0 and should install and run o.k. at least with basic data.

**Comment by cherylepatrick** [comment]
Thanks @drbenmorgan . It works great on my mac, just trying it on the linux box now.

**Comment by cherylepatrick** [comment]
Also seems fine on linux; happy to close this one.
