### ISSUE TITLE
Adding XXXConfig.cmake files

### ISSUE THREAD

**Issue by xgarrido** [SuperNEMO-DBD/homebrew-cadfael#2]
In the current [Cadfael version](https://nemo.lpc-caen.in2p3.fr/wiki/Software/Cadfael), the different ports install a bunch of cmake files such as [port]Config.cmake or [port]ConfigVersion.cmake. At the end the install directory of cadfael is populated by cmake scripts in the ```lib/cmake``` directory

```
├── Boost-1.55.0
│   ├── BoostConfig.cmake
│   ├── BoostConfigVersion.cmake
│   ├── BoostLibraryDepends-shared-multithread.cmake
│   └── BoostLibraryDepends-shared-multithread-release.cmake
├── CAMP-0.7.1
│   ├── CAMPConfig.cmake
│   ├── CAMPConfigVersion.cmake
│   ├── CAMPLibraryTargets.cmake
│   └── CAMPLibraryTargets-Release.cmake
├── GSL-1.15
│   ├── GSLConfig.cmake
│   ├── GSLConfigVersion.cmake
│   ├── GSLLibraryDepends.cmake
│   └── GSLLibraryDepends-Release.cmake
├── Patchelf-0.6
│   ├── PatchelfConfig.cmake
│   └── PatchelfConfigVersion.cmake
├── ROOT-5.34.32
│   ├── ROOTConfig.cmake
│   ├── ROOTConfigVersion.cmake
│   ├── ROOTLibraryDepends.cmake
│   └── ROOTLibraryDepends-Release.cmake
└── XercesC-3.1.2
    ├── XercesCConfig.cmake
    ├── XercesCConfigVersion.cmake
    ├── XercesCLibraryDepends.cmake
    └── XercesCLibraryDepends-Release.cmake
``` 

Maybe there will be a Bayeux/Falaise tap in a near future but I am wondering how hard it will be to add such features in order to further test ```cadfael-brew```. Currently, Bayeux installation at the configuration level saying

```
CMake Error at source/CMakeLists.txt:28 (find_package):
  Could not find a package configuration file provided by "Boost" (requested
  version 1.48.0) with any of the following names:

    BoostConfig.cmake
    boost-config.cmake

  Add the installation prefix of "Boost" to CMAKE_PREFIX_PATH or set
  "Boost_DIR" to a directory containing one of the above files.  If "Boost"
  provides a separate development package or SDK, be sure it has been
  installed.
```

**Comment by drbenmorgan** [comment]
Implemented for GSL, will add for Boost and XercesC. All other packages should now supply the relevant files by default.

**Comment by drbenmorgan** [comment]
Implemented for Boost

**Comment by drbenmorgan** [comment]
Implemented for Xerces-C...

**Comment by drbenmorgan** [comment]
Marking as fixed. Patchelf was only needed by old Cadfael for packaging, and with the new system we don't as yet need it in our own software.

ROOT is installed through CMake now and supplies its own ROOTConfig files. These have slightly different interfaces though, so will need to patch Falaise/Bayeux to use these.
