### ISSUE TITLE
Undefined reference to curl@CURL_OPENSSL

### ISSUE THREAD

**Issue by xgarrido** [SuperNEMO-DBD/homebrew-cadfael#26]
# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Confirmed this is a problem with specific formulae and not brew? If it's a general brew problem please file this issue at https://github.com/supernemo-dbd/brew/issues/new

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

After a successful ```brew update``` (so everything got installed well), I got link problems when building bayeux from source. Typical error messages are

```
[661/665] Linking CXX executable BuildProducts/bin/bxg4_production-3.0.0
/home/garrido/Workdir/NEMO/supernemo/snware/brew/lib/libxerces-c-3.1.so : undefined reference to « curl_easy_getinfo@CURL_OPENSSL_4 »
/home/garrido/Workdir/NEMO/supernemo/snware/brew/lib/libxerces-c-3.1.so : undefined reference to « curl_multi_perform@CURL_OPENSSL_4 »
/home/garrido/Workdir/NEMO/supernemo/snware/brew/lib/libxerces-c-3.1.so : undefined reference to « curl_multi_cleanup@CURL_OPENSSL_4 »
```

I also tried from a fresh installation of ```brew/cadfael``` from scratch with ```build-from-source``` flag to avoid the use of bottles and finally got the same issue. 

Here is the ```brew config```

```
HOMEBREW_VERSION: >1.2.0 (no git repository)
ORIGIN: https://github.com/SuperNEMO-DBD/brew.git
HEAD: 2bdfd11fd2663f58e6f4a63986344dd777b7c70f
Last commit: il y a 6 jours
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: d48874b4184ca4eb8ef803d1cb16323292c75f5d
Core tap last commit: il y a 10 heures
HOMEBREW_PREFIX: /home/garrido/Workdir/NEMO/supernemo/snware/brew
HOMEBREW_REPOSITORY: /home/garrido/Workdir/NEMO/supernemo/snware/brew
HOMEBREW_CELLAR: /home/garrido/Workdir/NEMO/supernemo/snware/brew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.4.2 => /usr/bin/ruby
Clang: N/A
Git: 2.14.1 => /usr/bin/git
Perl: /usr/bin/perl
Python: /home/garrido/Workdir/NEMO/supernemo/snware/brew/opt/python/libexec/bin/python => /home/garrido/Workdir/NEMO/supernemo/snware/brew/Cellar/python/2.7.13_1/bin/python2.7
Ruby: /usr/bin/ruby
Java: 1.7.0_151
Kernel: Linux 4.12.13-1-ARCH x86_64 GNU/Linux
OS: Arch Linux (n/a)
Host glibc: 2.26
/usr/bin/gcc: 7.2.0
glibc: N/A
gcc: N/A
xorg: N/A
```

**Comment by drbenmorgan** [comment]
I *think* this is also certainly due to the `xerces-c` formula missing a dependency on `curl`. I'll prepare a patch for this.

**Comment by drbenmorgan** [comment]
O.k., the "Fixes" construct really does close issues! If you can try `brew update` and check that `xerces-c`, `geant4`, `bayeux` and `falaise` are marked as outdated, a `brew upgrade` should work. If not, reopen the issue.
