### ISSUE TITLE
root6 installation failed

### ISSUE THREAD

**Issue by victortretyak** [SuperNEMO-DBD/homebrew-cadfael#29]
Tried to install Falaise, version 3.1.1 with Home/Linuxbrew under Ubuntu 16.04.
Succesfully executed:
$ git clone https://github.com/SuperNEMO-DBD/brew.git cadfaelbrew
$ cd cadfaelbrew
$ ./bin/brew cadfael-bootstrap

Then:
$ ./bin/brew install falaise
finished with error:

==> Downloading http://root.cern.ch/download/root_v6.08.06.source.tar.gz
Already downloaded: /home/tretyak/.cache/Homebrew/root6-6.08.06.tar.gz
==> cmake .. -Dalien=OFF -Dasimage=OFF -Dastiff=OFF -Dbonjour=OFF -Dcastor=OFF -
==> make install
Last 15 lines from /home/tretyak/.cache/Homebrew/Logs/root6/02.make:
-- FFTW3 build command succeeded.  See also /tmp/root6-20170928-14654-1l8ixhd/root-6.08.06/cmake-build/FFTW3-prefix/src/FFTW3-stamp/FFTW3-build-*.log
cd /tmp/root6-20170928-14654-1l8ixhd/root-6.08.06/cmake-build/FFTW3-prefix/src/FFTW3 && /home/tretyak/cadfaelbrew/Cellar/cmake/3.9.3_1/bin/cmake -E touch /tmp/root6-20170928-14654-1l8ixhd/root-6.08.06/cmake-build/FFTW3-prefix/src/FFTW3-stamp/./FFTW3-build
[ 24%] Performing install step for 'FFTW3'
cd /tmp/root6-20170928-14654-1l8ixhd/root-6.08.06/cmake-build/FFTW3-prefix/src/FFTW3 && /home/tretyak/cadfaelbrew/Cellar/cmake/3.9.3_1/bin/cmake -Dmake=make -P /tmp/root6-20170928-14654-1l8ixhd/root-6.08.06/cmake-build/FFTW3-prefix/src/FFTW3-stamp/FFTW3-install-Release.cmake
-- FFTW3 install command succeeded.  See also /tmp/root6-20170928-14654-1l8ixhd/root-6.08.06/cmake-build/FFTW3-prefix/src/FFTW3-stamp/FFTW3-install-*.log
cd /tmp/root6-20170928-14654-1l8ixhd/root-6.08.06/cmake-build/FFTW3-prefix/src/FFTW3 && /home/tretyak/cadfaelbrew/Cellar/cmake/3.9.3_1/bin/cmake -E touch /tmp/root6-20170928-14654-1l8ixhd/root-6.08.06/cmake-build/FFTW3-prefix/src/FFTW3-stamp/./FFTW3-install
[ 24%] Completed 'FFTW3'
/home/tretyak/cadfaelbrew/Cellar/cmake/3.9.3_1/bin/cmake -E make_directory /tmp/root6-20170928-14654-1l8ixhd/root-6.08.06/cmake-build/CMakeFiles/.
/home/tretyak/cadfaelbrew/Cellar/cmake/3.9.3_1/bin/cmake -E touch /tmp/root6-20170928-14654-1l8ixhd/root-6.08.06/cmake-build/CMakeFiles/./FFTW3-complete
/home/tretyak/cadfaelbrew/Cellar/cmake/3.9.3_1/bin/cmake -E touch /tmp/root6-20170928-14654-1l8ixhd/root-6.08.06/cmake-build/FFTW3-prefix/src/FFTW3-stamp/./FFTW3-done
make[2]: Leaving directory '/tmp/root6-20170928-14654-1l8ixhd/root-6.08.06/cmake-build'
[ 24%] Built target FFTW3
make[1]: Leaving directory '/tmp/root6-20170928-14654-1l8ixhd/root-6.08.06/cmake-build'
Makefile:154: recipe for target 'all' failed
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/supernemo-dbd/homebrew-cadfael/issues
---------------------------------
./bin/brew config
HOMEBREW_VERSION: >1.2.0 (no git repository)
ORIGIN: https://github.com/SuperNEMO-DBD/brew.git
HEAD: 2bdfd11fd2663f58e6f4a63986344dd777b7c70f
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: ebcede77b4ddfd1132b6b10a789279dc209ac205
Core tap last commit: 67 minutes ago
HOMEBREW_PREFIX: /home/tretyak/cadfaelbrew
HOMEBREW_REPOSITORY: /home/tretyak/cadfaelbrew
HOMEBREW_CELLAR: /home/tretyak/cadfaelbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: octa-core 64-bit 0x69e
Homebrew Ruby: 2.3.1 => /usr/bin/ruby2.3
Clang: N/A
Git: 2.7.4 => /usr/bin/git
Perl: /usr/bin/perl
Python: /home/tretyak/cadfaelbrew/opt/python/libexec/bin/python => /home/tretyak/cadfaelbrew/Cellar/python/2.7.14/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby2.3
Java: openjdk version "1.8.0_131"
Kernel: Linux 4.10.0-35-generic x86_64 GNU/Linux
OS: Ubuntu 16.04.3 LTS (xenial)
Host glibc: 2.23
/usr/bin/gcc: 5.4.0
glibc: N/A
gcc: N/A
xorg: N/A

./bin/brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have HOMEBREW_BUILD_FROM_SOURCE set. This environment variable is
intended for use by Homebrew developers. If you are encountering errors,
please try unsetting this. Please do not file issues if you encounter
errors when using this environment variable.

./bin/brew gist-logs root6
https://gist.github.com/8374b7473d83e506e923f8ca0aed4273

./bin/brew gist-logs falaise
Error: No logs.

Retried `brew update` and `brew doctor`, it does not help.

**Comment by drbenmorgan** [comment]
Thanks for the logs! The error is due to `g77` being present in `/usr/bin` and the `root6` formula automatically activating Fortran support based on its presence. I'll prepare a patch to explicitly disable Fortran support.

**Comment by drbenmorgan** [comment]
Please try

```
$ brew update
$ brew install falaise
```

again. The `root6` formula should now have the needed fix in.

**Comment by victortretyak** [comment]
Thank you. The problem is solved now (after "brew update") .
There was a warning about icu4c :
==> Installing supernemo-dbd/cadfael/falaise
==> Downloading https://github.com/SuperNEMO-DBD/Falaise/archive/Falaise-3.1.1.t
==> Downloading from https://codeload.github.com/SuperNEMO-DBD/Falaise/tar.gz/Fa
######################################################################## 100.0%
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
==> make install
Warning: supernemo-dbd/cadfael/falaise dependency icu4c was built with a different C++ standard
library (libstdc++ from c_compiler). This may cause problems at runtime.
\U0001f37a  /home/tretyak/cadfaelbrew/Cellar/falaise/3.1.1: 1,650 files, 85.7MB, built in 1 minute 33 seconds

Don't know if I really should worry about icu4c.  The test:
./bin/brew test falaise
passed smoothly
