### ISSUE TITLE
Root6 failed installation 

### ISSUE THREAD

**Issue by Tedjditi** [SuperNEMO-DBD/homebrew-cadfael#31]
Dears developers, 

I tried to install falaise with Homebrew-cadfael on SL6.

I successfully executed:

$ git clone https://github.com/SuperNEMO-DBD/brew.git ~/CadfaelBrew
$ cd CadfaelBrew/
$ ./bin/brew cadfael-bootstrap

Then:
$ ./bin/brew install falaise
ended with the error attached in the file
[Errorlog.txt](https://github.com/SuperNEMO-DBD/homebrew-cadfael/files/1378788/Errorlog.txt)

Result of the ./bin/brew config :

HOMEBREW_VERSION: >1.2.0 (no git repository)
ORIGIN: https://github.com/SuperNEMO-DBD/brew.git
HEAD: 2bdfd11fd2663f58e6f4a63986344dd777b7c70f
Last commit: 4 weeks ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 17f2c53ff2a61e2518de9212aa521ffd6a8d4df3
Core tap last commit: 25 hours ago
HOMEBREW_PREFIX: /snemo/tedjditi/CadfaelBrew
HOMEBREW_REPOSITORY: /snemo/tedjditi/CadfaelBrew
HOMEBREW_CELLAR: /snemo/tedjditi/CadfaelBrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: dual-core 64-bit penryn
Homebrew Ruby: 2.0.0-p648 => /snemo/tedjditi/CadfaelBrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
Clang: N/A
Git: 2.14.2 => /snemo/tedjditi/CadfaelBrew/bin/git
Perl: /usr/local/bin/perl => /usr/bin/perl
Python: /snemo/tedjditi/CadfaelBrew/opt/python/libexec/bin/python => /snemo/tedjditi/CadfaelBrew/Cellar/python/2.7.14/bin/python2.7
Ruby: /snemo/tedjditi/CadfaelBrew/bin/ruby => /snemo/tedjditi/CadfaelBrew/Cellar/ruby/2.4.2/bin/ruby
Java: 1.7.0_151
Kernel: Linux 2.6.32-696.10.3.el6.x86_64 x86_64 GNU/Linux
OS: Scientific Linux release 6.9 (Carbon) (Carbon)
Host glibc: 2.12
/usr/bin/gcc: 4.4.7
glibc: N/A
gcc: N/A
xorg: N/A

Output of ./bin/brew doctor

[BrewDoctor.txt](https://github.com/SuperNEMO-DBD/homebrew-cadfael/files/1378802/BrewDoctor.txt)

https://gist.github.com/09b374285addf03b1051a540140bbde1

The last Brew update was done yesterday.

Thanks for your help.

**Comment by cherylepatrick** [comment]
@Tedjditi Totally unrelated to fixing your issue, but I am maintaining a directory of current collaboration members on the SuperNEMO website . As I don't recognise your login, I am wondering if you might be a new person I don't have on my list. If that's the case, can you mail me at c.patrick@ucl.ac.uk and let me know your name, email address (and if it's ok to include it on the website), institution and, if you like, a photo and your role/interests on the experiment. (E.g. "PhD student, interested in calorimeters"). Thanks and good luck with the installation!

**Comment by drbenmorgan** [comment]
The error seems to be due to the root configure script picking up `png` from `/usr/local`, as warned by `brew doctor`. If possible, remove all of the installed software under `/usr/local` as this will interfere with both system and brewed installs - plus, everything there is horribly out of date.

If you can't remove stuff there, try

```
$ brew install libpng
$ brew install falaise
```

This may not work, but please report in either case with the gist logs as before.

**Comment by Tedjditi** [comment]
Thank you for the answer,

I tried : 

$ brew install libpng
$ brew install falaise

and Root6 correctly installed.
