### ISSUE TITLE
Different root 6 failure

### ISSUE THREAD

**Issue by cherylepatrick** [SuperNEMO-DBD/homebrew-cadfael#32]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is a problem with specific formulae and not brew? 

`brew upgrade bayeux ` is failing and the failure is coming with root 6. This is bad news for me because I can now no longer use falaise (the old version is still in the cellar but won't run, and the new version is not in the cellar). Pertinent(?) info:

- Old falaise install that was working OK: 3.0.0
- Root version already on there (and still apparently working, or at least starting) 6.08/06 (isn't this the same as it was trying to install?)
- Mac OSX Sierra 10.12.6 (16G29)
- Xcode 8.3.3 (BUT I am suspicious of this. Xcode definitely reports that version number. If I try to check the version of my Xcode command line tools it matches Lauren's, who just downgraded to 8.3.3. But before I tried this upgrade I attempted to build an flreconstruct module that used to build just fine, and it failed with the same TString errors that Lauren saw when she tried to build it against Xcode 9).

Will post the output of various things as comments

**Comment by cherylepatrick** [comment]
[Result of `brew gist-logs root6`](https://gist.github.com/cherylepatrick/b78b09ee61b16d0479ee62337c5a92f3)

**Comment by cherylepatrick** [comment]
Result of `brew doctor`:

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /opt/ImageMagick/bin/Magick++-config
  /opt/ImageMagick/bin/Magick-config
  /opt/ImageMagick/bin/MagickCore-config
  /opt/ImageMagick/bin/MagickWand-config
  /opt/ImageMagick/bin/Wand-config

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  falaise

Warning: Your Homebrew's prefix is not /usr/local.
You can install Homebrew anywhere you want but some bottles (binary packages)
can only be used with a /usr/local prefix and some formulae (packages)
may not build correctly with a non-/usr/local prefix.

**Comment by cherylepatrick** [comment]
Result of `brew config`:
HOMEBREW_VERSION: 1.1.13-956-g2bdfd11
ORIGIN: https://github.com/SuperNEMO-DBD/brew.git
HEAD: 2bdfd11fd2663f58e6f4a63986344dd777b7c70f
Last commit: 4 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5b77af770999f089a53b75cb776f82fd093fe6e3
Core tap last commit: 38 minutes ago
HOMEBREW_PREFIX: /Users/cpatrick/CadfaelBrew
HOMEBREW_REPOSITORY: /Users/cpatrick/CadfaelBrew
HOMEBREW_CELLAR: /Users/cpatrick/CadfaelBrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 9.0 build 900
Git: 2.13.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /Users/cpatrick/CadfaelBrew/opt/python/libexec/bin/python => /Users/cpatrick/CadfaelBrew/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.6-x86_64
Xcode: 8.3.3
CLT: 9.0.0.0.1.1504363082
X11: 2.7.11 => /opt/X11

**Comment by drbenmorgan** [comment]
I think the issue is that Xcode 8.3 is in use but the command line tools are version 9 (see `brew config`). Certainly, the error message in root6 relates to the Xcode 9 issue. Check the output of

```
$ clang++ --version
```

on the command line. If it prints anything related to `9` or `900`, then the CLT are using version 9. The resolution should be to run, on the command line:

```
$ sudo xcode-select -s /pathtoyourXcode8install
```

for example, I have Xcode 8.3 install as `/Applications/Xcode8.3.app` so do

```
$ sudo xcode-select -s /Applications/Xcode8.3.app
```

After switching, try

```
$ clang++ --version
```

again and confirm the version.

**Comment by cherylepatrick** [comment]
Thanks Ben! That makes sense, as it would also explain why I was seeing the Xcode 9 -like root errors before. Didn't pick up on "CLT" being the Xcode command line tools. Not sure how they got out of step either, but hopefully the fix will work. Will try tonight (it's on my home computer so I can't check it now). Thanks again for your help.

**Comment by cherylepatrick** [comment]
Well it's definitely better, thanks @drbenmorgan ! As far as I can tell the install went OK, but (there is always a but, isn't there?)...

It looks like I have an installation of Falaise now, but I'm not sure if it is the right one? Maybe I should have done something other than just `brew upgrade`? There's no flsimulate etc symlinked in the `bin` folder, and in the Cellar there's an install from today labeled `HEAD-83070c6` but no `3.1.1`. Did I do something wrong?

**Comment by drbenmorgan** [comment]
@cherylepatrick I think because you've previously installed a `HEAD` version (i.e. tracks the `develop` branch), it's upgraded that. The commit referenced, `83070c6`, is post-3.1.1. Two options:

1. If you want to keep tracking the `develop` branch, keep the `HEAD` install and try `brew link falaise`. 
2. If you want the stable version, do `brew rm falaise && brew install falaise`. That should remove the `HEAD` install and reinstall `3.1.1`.

**Comment by cherylepatrick** [comment]
I'll stick with the HEAD for now... and that worked, thanks!
