### ISSUE TITLE
Fontconfig failed installation 

### ISSUE THREAD

**Issue by Tedjditi** [SuperNEMO-DBD/homebrew-cadfael#33]
Dears developers,

I tried to install Falaise with Homebrew-cadfael on SL6.

I successfully executed:

$ git clone https://github.com/SuperNEMO-DBD/brew.git ~/CadfaelBrew
$ cd CadfaelBrew/
$ ./bin/brew cadfael-bootstrap

Then:
$ ./bin/brew install falaise

I had an error with the root6 installation wich is now fixed: https://github.com/SuperNEMO-DBD/homebrew-cadfael/issues/31

But it ended with:

[ErrorFontconfig.txt](https://github.com/SuperNEMO-DBD/homebrew-cadfael/files/1387009/ErrorFontconfig.txt)

Result of the ./bin/brew config :

HOMEBREW_VERSION: >1.2.0 (no git repository)
ORIGIN: https://github.com/SuperNEMO-DBD/brew.git
HEAD: 2bdfd11fd2663f58e6f4a63986344dd777b7c70f
Last commit: 4 weeks ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 17f2c53ff2a61e2518de9212aa521ffd6a8d4df3
Core tap last commit: 25 hours ago
HOMEBREW_PREFIX: /snemo/tedjditi/CadfaelBrew
HOMEBREW_REPOSITORY: /snemo/tedjditi/CadfaelBrew
HOMEBREW_CELLAR: /snemo/tedjditi/CadfaelBrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: dual-core 64-bit penryn
Homebrew Ruby: 2.0.0-p648 => /snemo/tedjditi/CadfaelBrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
Clang: N/A
Git: 2.14.2 => /snemo/tedjditi/CadfaelBrew/bin/git
Perl: /usr/local/bin/perl => /usr/bin/perl
Python: /snemo/tedjditi/CadfaelBrew/opt/python/libexec/bin/python => /snemo/tedjditi/CadfaelBrew/Cellar/python/2.7.14/bin/python2.7
Ruby: /snemo/tedjditi/CadfaelBrew/bin/ruby => /snemo/tedjditi/CadfaelBrew/Cellar/ruby/2.4.2/bin/ruby
Java: 1.7.0_151
Kernel: Linux 2.6.32-696.10.3.el6.x86_64 x86_64 GNU/Linux
OS: Scientific Linux release 6.9 (Carbon) (Carbon)
Host glibc: 2.12
/usr/bin/gcc: 4.4.7
glibc: N/A
gcc: N/A
xorg: N/A

Output of the /brew doctor:

[OutputDoctor.txt](https://github.com/SuperNEMO-DBD/homebrew-cadfael/files/1387226/OutputDoctor.txt)

https://gist.github.com/f0a65cdffc47a43c5ed1ed98fc5f3b1a

Thank for your help

**Comment by drbenmorgan** [comment]
Try 

```
$ brew install fontconfig --without-docs
```

The correct set of rpms should be installed given that the `cadfael-bootstrap` step passed, but this should get font-config installed.

**Comment by Tedjditi** [comment]
It worked.
This problem has also been reported with LinuxBrew. Here the link to their issue.
https://github.com/Linuxbrew/legacy-linuxbrew/issues/824

Thank you.
