### ISSUE TITLE
cadfael and brew install failed at CCLYON

### ISSUE THREAD

**Issue by lemiere** [SuperNEMO-DBD/homebrew-cadfael#34]
At CCLYON (SL6), I'm trying to install from scratch simulation software and it failed (again)
Up to now, I'm not able to ensure new falaise version.

Any idea ? 
Yves,

**brew install unzip**---> 

Error: gpatch: /sps/nemo/sw/simulation/install_brew/10-2017/cadfaelbrew/Library/Taps/homebrew/homebrew-core/Formula/gpatch.rb:25: syntax error, unexpected <<
    patch = <<~EOS
              ^
/sps/nemo/sw/simulation/install_brew/10-2017/cadfaelbrew/Library/Taps/homebrew/homebrew-core/Formula/gpatch.rb:26: syntax error, unexpected tIDENTIFIER, expecting keyword_end
/sps/nemo/sw/simulation/install_brew/10-2017/cadfaelbrew/Library/Taps/homebrew/homebrew-core/Formula/gpatch.rb:29: syntax error, unexpected '>'
      > hello
       ^

**brew update** --> already up to date
**brew doctor** --> Error: git: /sps/nemo/sw/simulation/install_brew/10-2017/cadfaelbrew/Library/Taps/homebrew/homebrew-core/Formula/git.rb:209: syntax error, unexpected $undefined, expecting keyword_end
      \thelper = osxkeychain
       ^

**Comment by drbenmorgan** [comment]
Looks like brew needed updating - please run `brew update` again, and things should resolve. Otherwise, try a fresh checkout.
