### ISSUE TITLE
Root6 installation failed on Debian9

### ISSUE THREAD

**Issue by Tedjditi** [SuperNEMO-DBD/homebrew-cadfael#35]
Dears developers,

I tried to install falaise with Homebrew-cadfael on Debian9.

I successfully executed:

$ git clone https://github.com/SuperNEMO-DBD/brew.git ~/CadfaelBrew
$ cd CadfaelBrew/
$ ./bin/brew cadfael-bootstrap

Then:
$ ./bin/brew install falaise
ended with the error attached in the file
[ErrorLog.txt](https://github.com/SuperNEMO-DBD/homebrew-cadfael/files/1426929/ErrorLog.txt)

Result of the ./bin/brew config :

[Config.txt](https://github.com/SuperNEMO-DBD/homebrew-cadfael/files/1426934/Config.txt)

Output of ./bin/brew doctor:
[Doctor.txt](https://github.com/SuperNEMO-DBD/homebrew-cadfael/files/1426943/Doctor.txt)

https://gist.github.com/09b374285addf03b1051a540140bbde1

Brew update output is : "Already up-to-date

Thank you for your help.

**Comment by drbenmorgan** [comment]
Could you upload a new Gist please? The linked one points to a previous one for CentOS 6.9, not Debian 9.

**Comment by Tedjditi** [comment]
https://gist.github.com/2468d0ad1fd4f2cd1d3f3332f41b7e19

Sorry.

**Comment by Tedjditi** [comment]
I installed root6 v6-08-06 from Root public Git repertory : 
https://root.cern.ch/content/release-60806

root6 installation succeeded (but brew install root6 did not succeed before)
i redo brew install falaise
and it suceed.
brew test falaise passed smoothly too.
