### ISSUE TITLE
cadfael-bootstrap fails when building libxml2

### ISSUE THREAD

**Issue by edbird** [SuperNEMO-DBD/homebrew-cadfael#39]
Seem to encounter an error when bootstrapping on (a) Debian 9 system, which is weird because I have already got falaise installed on another Debian 9 system. (Now trying to install on a laptop which has been around a while with this OS, which probably means something else I installed at some point is now causing problems.)

The error is Python.h no such file or directory, but `find /usr -name "Python.h"` produces this:

/usr/include/python2.7/Python.h
/usr/include/python3.5m/Python.h
/usr/lib/pypy/include/Python.h

The last of those lines I installed today while google-ing for possible reasons for this error...

In addition: ./bin/brew install python produces:

Warning: python 2.7.14 is already installed

Even weirder: sudo apt install libxml2 libxml2-dev reports that these are already installed. (by apt)

Notes: No issues in brew doctor, have already run brew update.

./bin/brew cadfaelbrew-bootstrap fails when building libxml2

==> Installing git-flow-avh dependency: libxml2
==> Downloading http://xmlsoft.org/sources/libxml2-2.9.7.tar.gz
Already downloaded: /home/ecb/.cache/Homebrew/libxml2-2.9.7.tar.gz
==> ./configure --prefix=/home/ecb/cadfaelbrew/Cellar/libxml2/2.9.7 --without-python --without-lzma
==> make install
==> python setup.py install --prefix=/home/ecb/cadfaelbrew/Cellar/libxml2/2.9.7
Last 15 lines from /home/ecb/.cache/Homebrew/Logs/libxml2/03.python:
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
copying libxml2.py -> build/lib.linux-x86_64-2.7
copying drv_libxml2.py -> build/lib.linux-x86_64-2.7
running build_ext
building 'libxml2mod' extension
creating build/temp.linux-x86_64-2.7
gcc-6 -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -D_REENTRANT=1 -I/home/ecb/cadfaelbrew/Cellar/libxml2/2.9.7/include/libxml2 -I/usr/include -I/usr/include/python2.7 -c libxml2-py.c -o build/temp.linux-x86_64-2.7/libxml2-py.o
libxml2-py.c:3:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
error: command 'gcc-6' failed with exit status 1

READ THIS: https://github.com/SuperNEMO-DBD/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

brew config output:

HOMEBREW_VERSION: >1.2.0 (shallow or no git repository)
ORIGIN: https://github.com/SuperNEMO-DBD/brew.git
HEAD: fb15d3b119ee73824a21c2e721c6629d6d91aff0
Last commit: 2 months ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 4db5ca634b9f9bcb1cb30f157164b426a3f79fe6
Core tap last commit: 56 minutes ago
HOMEBREW_PREFIX: /home/ecb/cadfaelbrew
HOMEBREW_REPOSITORY: /home/ecb/cadfaelbrew
HOMEBREW_CELLAR: /home/ecb/cadfaelbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.3.3 => /usr/bin/ruby2.3
Clang: N/A
Git: 2.11.0 => /usr/bin/git
Perl: /usr/bin/perl
Python: /home/ecb/cadfaelbrew/opt/python/libexec/bin/python => /home/ecb/cadfaelbrew/Cellar/python/2.7.14/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby2.3
Java: openjdk version "1.8.0_151"
Kernel: Linux 4.9.0-4-amd64 x86_64 GNU/Linux
OS: Debian GNU/Linux 9.3 (stretch) (stretch)
Host glibc: 2.24
/usr/bin/gcc: 6.3.0
glibc: N/A
gcc: N/A
xorg: N/A

brew doctor output:

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have HOMEBREW_BUILD_FROM_SOURCE set. This environment variable is
intended for use by Homebrew developers. If you are encountering errors,
please try unsetting this. Please do not file issues if you encounter
errors when using this environment variable.

Warning: Homebrew's share was not found in your XDG_DATA_DIRS but you have
this variable set to include other locations.
Some programs like `vapigen` may not work correctly.
Consider setting the XDG_DATA_DIRS for example like so
    echo 'export XDG_DATA_DIRS="/home/ecb/cadfaelbrew/share:$XDG_DATA_DIRS"' >> ~/.bash_profile

Not sure if those warnings are relevant? I seem to remember them appearing on 

./bin/brew gist-logs libxml2: https://gist.github.com/fc1a3f97daf24afd4e5781bf708c049e

**Comment by drbenmorgan** [comment]
This should now be fixed in `brew` (see https://github.com/Linuxbrew/brew/pull/555, which is now merged). 

Please reopen if a `brew update` and re-bootstrapping etc does not work.
