### ISSUE TITLE
unable to install clang

### ISSUE THREAD

**Issue by lemiere** [SuperNEMO-DBD/homebrew-cadfael#42]
I would like install Falaise/PR82 
Requirements are : new Bayeux features (3.1.1) and clang
So I did : 
`brew update
brew install clang-format
`

The issue is : 
`
==> Cloning http://llvm.org/svn/llvm-project/llvm/tags/google/stable/2017-11-1
svn: E170013: Unable to connect to a repository at URL 'http://llvm.org/svn/llvm-project/llvm/tags/google/stable/2017-11-14'
svn: E000111: Error running context: Connection refused
Error: Failed to download resource "clang-format"
Failure while executing: svn checkout -q http://llvm.org/svn/llvm-project/llvm/tags/google/stable/2017-11-14/ /home/lemiere/.cache/Homebrew/clang-format--svn
`
Even if using Firefox I can reach : http://llvm.org/svn/llvm-project/llvm/tags/google/stable/2017-11-14/

#### For your information : 
`brew doctor
 brew config
HOMEBREW_VERSION: >=1.4.0 (shallow or no git repository)
ORIGIN: https://github.com/SuperNEMO-DBD/brew
HEAD: fb91295399c74e6b42a8453093428517c8b24055
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 83775c337383f4d31bdcd6bfdd077b5173d48749
Core tap last commit: 11 hours ago
HOMEBREW_PREFIX: /home/lemiere/sofware/NEMO/simulation/3.0/cadfaelbrew
HOMEBREW_REPOSITORY: /home/lemiere/sofware/NEMO/simulation/3.0/cadfaelbrew
HOMEBREW_CELLAR: /home/lemiere/sofware/NEMO/simulation/3.0/cadfaelbrew/Cellar
HOMEBREW_BUILD_FROM_SOURCE: 1
HOMEBREW_CACHE: /home/lemiere/.cache/Homebrew
HOMEBREW_CELLAR: /home/lemiere/sofware/NEMO/simulation/3.0/cadfaelbrew/Cellar
HOMEBREW_NO_ANALYTICS: 1
HOMEBREW_PREFIX: /home/lemiere/sofware/NEMO/simulation/3.0/cadfaelbrew
HOMEBREW_REPOSITORY: /home/lemiere/sofware/NEMO/simulation/3.0/cadfaelbrew
CPU: quad-core 64-bit 0x64e
Homebrew Ruby: 2.3.3 => /home/lemiere/sofware/NEMO/simulation/3.0/cadfaelbrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: N/A
Git: 2.7.4 => /usr/bin/git
Curl: 7.57.0 => /home/lemiere/sofware/NEMO/simulation/3.0/cadfaelbrew/opt/curl/bin/curl
Perl: /home/lemiere/sofware/NEMO/simulation/3.0/cadfaelbrew/bin/perl => /home/lemiere/sofware/NEMO/simulation/3.0/cadfaelbrew/Cellar/perl/5.26.1/bin/perl
Python: /home/lemiere/sofware/NEMO/simulation/3.0/cadfaelbrew/opt/python/libexec/bin/python => /home/lemiere/sofware/NEMO/simulation/3.0/cadfaelbrew/Cellar/python/2.7.14_3/bin/python2.7
Ruby: /home/lemiere/sofware/NEMO/simulation/3.0/cadfaelbrew/bin/ruby => /home/lemiere/sofware/NEMO/simulation/3.0/cadfaelbrew/Cellar/ruby/2.5.0/bin/ruby
Java: openjdk version "1.8.0_151"
Kernel: Linux 4.4.0-112-generic x86_64 GNU/Linux
OS: Ubuntu 16.04.1 LTS (xenial)
Host glibc: 2.23
/usr/bin/gcc: 5.4.0
glibc: N/A
gcc: N/A
xorg: N/A
`

Thx for your help!

**Comment by drbenmorgan** [comment]
@lemiere, possibly a network issue, I've been able to install `clang-format` o.k. here.

Worst case, you can also install `clang-format` from Xenial's repos. Falaise won't care where it comes from!

**Comment by lemiere** [comment]
That's what I did!
