### ISSUE TITLE
Installation failed for CentOS 7

### ISSUE THREAD

**Issue by robobre** [SuperNEMO-DBD/homebrew-cadfael#44]
**Dears developers,
I have tried install homebrew-cadfael for CentOS 7 site follow instructions:
The installation finished with error:**

 ./bin/brew cadfael-bootstrap
==> Detected 'Linux' Operating System
==> Distribution 'CentOS (7.4.1708)'
==> System supported
==> Checking system software for RedHat7 (CentOS)
==> Checking for install of rpm 'expat-devel': expat-devel-2.1.0-10.el7_3
==> Checking for install of rpm 'git': git-1.8.3.1-12.el7_4
==> Checking for install of rpm 'openssl-devel': openssl-devel-1.0.2k-8.el7
==> Checking for install of rpm 'redhat-lsb-core': redhat-lsb-core-4.1-27.el7.centos.1
==> Checking for install of rpm 'ruby-irb': ruby-irb-2.0.0.648-30.el7
==> Checking for install of rpm 'glibc-static': glibc-static-2.17-196.el7_4.2
==> Checking for install of rpm 'libstdc++-static': libstdc++-static-4.8.5-16.el7_4.1
==> Checking for install of rpm 'which': which-2.20-7.el7
==> Checking for install of rpm 'HEP_OSlibs': HEP_OSlibs-7.2.4-1.el7.cern
==> Checking for install of Yum Group 'Development tools': Installed
==> Bootstrapping brew
==> System ruby (/usr/bin/ruby) version : 2.0
==> System ruby o.k.
==> Creating system compiler softlinks for bootstrapping
ln: failed to create symbolic link ‘/home/b/breier1/cadfaelbrew/bin/gcc-4.8’: File exists
Warning: Failed to create softlink to system gcc
ln: failed to create symbolic link ‘/home/b/breier1/cadfaelbrew/bin/g++-4.8’: File exists
Warning: Failed to create softlink to system g++
==> System git (/usr/bin/git) version : 1.8
==> System git o.k.
Already up-to-date.
==> About to bootstrap cadfael toolchain. This may take some time
==> Bootstrapping Cadfael toolchain
Error: undefined method `default_formula' for #<GCCRequirement: "gcc" []>
/home/b/breier1/cadfaelbrew/Library/Taps/supernemo-dbd/homebrew-cadfael/cmd/brew-cadfael-bootstrap-toolchain.rb:85:in `<top (required)>'
/home/b/breier1/cadfaelbrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/b/breier1/cadfaelbrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/b/breier1/cadfaelbrew/Library/Homebrew/utils.rb:20:in `require?'
/home/b/breier1/cadfaelbrew/Library/Homebrew/brew.rb:106:in `<main>'
Error: Failed to bootstrap cadfael toolchain

 **brew doctor**           
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have HOMEBREW_BUILD_FROM_SOURCE set. This environment variable is
intended for use by Homebrew developers. If you are encountering errors,
please try unsetting this. Please do not file issues if you encounter
errors when using this environment variable.

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /bin/libpng15-config
  /bin/ncursesw5-config
  /bin/libpng-config
  /bin/pcre-config
  /bin/pkg-config
  /bin/ncurses5-config
  /bin/freetype-config
  /bin/ijs-config
  /bin/krb5-config
  /bin/xml2-config

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/attr_node_func.h
  /usr/local/include/catch_child.h
  /usr/local/include/checkpoint.h
  /usr/local/include/chk_file_sec.h
  /usr/local/include/lib_ifl.h
  /usr/local/include/lib_mom.h
  /usr/local/include/lib_net.h
  /usr/local/include/lib_utils.h
  /usr/local/include/log_event.h
  /usr/local/include/mom_comm.h
  /usr/local/include/mom_job_func.h
  /usr/local/include/mom_main.h
  /usr/local/include/mom_process_request.h
  /usr/local/include/mom_server_lib.h
  /usr/local/include/pbs_log.h
  /usr/local/include/prolog.h
  /usr/local/include/setup_env.h
  /usr/local/include/u_lock_ctl.h

**and  
 brew config**    
HOMEBREW_VERSION: >=1.4.0 (shallow or no git repository)
ORIGIN: https://github.com/SuperNEMO-DBD/brew.git
HEAD: 9acc3eba1ad1f9778f449eff70a7a6e201c3fe47
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 547b634b8eefad8ef07264b60fb2ee9e196d3297
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /home/b/breier1/cadfaelbrew
HOMEBREW_REPOSITORY: /home/b/breier1/cadfaelbrew
HOMEBREW_CELLAR: /home/b/breier1/cadfaelbrew/Cellar
HOMEBREW_BUILD_FROM_SOURCE: 1
HOMEBREW_CACHE: /home/b/breier1/.cache/Homebrew
HOMEBREW_CELLAR: /home/b/breier1/cadfaelbrew/Cellar
HOMEBREW_NO_ANALYTICS: 1
HOMEBREW_PREFIX: /home/b/breier1/cadfaelbrew
HOMEBREW_REPOSITORY: /home/b/breier1/cadfaelbrew
CPU: quad-core 64-bit westmere
Homebrew Ruby: 2.3.3 => /home/b/breier1/cadfaelbrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 3.4 build 
Git: 2.16.1 => /home/b/breier1/cadfaelbrew/bin/git
Curl: 7.58.0 => /home/b/breier1/cadfaelbrew/opt/curl/bin/curl
Perl: /home/b/breier1/cadfaelbrew/bin/perl => /home/b/breier1/cadfaelbrew/Cellar/perl/5.26.1/bin/perl
Python: /bin/python => /usr/bin/python2.7
Ruby: /bin/ruby => /usr/bin/ruby
Java: N/A
Kernel: Linux 3.10.0-514.26.2.el7.x86_64 x86_64 GNU/Linux
OS: CentOS Linux release 7.4.1708 (Core)  (Core)
Host glibc: 2.17
/usr/bin/gcc: 4.8.5
glibc: N/A
gcc: N/A
xorg: N/A

**I have also tried install falaise with enable devtoolset-4. The ./bin/brew cadfael-bootstrap was finished ok, but  installation of falaise fell on qt5-base with error:**

Last 15 lines from /home/b/breier1/.cache/Homebrew/Logs/qt5-base/01.configure:
  InterBase .............................. no
  MySql .................................. no
  OCI (Oracle) ........................... no
  ODBC ................................... no
  PostgreSQL ............................. no
  SQLite2 ................................ no
  SQLite ................................. yes
    Using system provided SQLite ......... no
  TDS (Sybase) ........................... no

Note: Also available for Linux: linux-clang linux-icc

Note: Disabling X11 Accessibility Bridge: D-Bus or AT-SPI is missing.

ERROR: Feature 'c++14' was enabled, but the pre-condition 'features.c++11 && tests.c++14' failed.

**Thank you in advance
Cheers
       Robert**

**Comment by drbenmorgan** [comment]
Fixed by 8c2b743
