### ISSUE TITLE
homebrew-cadfael broken on CentOS7

### ISSUE THREAD

**Issue by emchauve** [SuperNEMO-DBD/homebrew-cadfael#50]
Impossible to tap homebrew/core on CentOS7 (so can not run brew update, doctor, etc.) when doing a new install from scratch.  Issue is related to an unitialised variable Homebrew::DEFAULT_PREFIX in the formula given bellow :

```
==> Tapping homebrew/core
Cloning into '/home/chauveau/cadfaelbrew/Library/Taps/homebrew/homebrew-core'...
remote: Enumerating objects: 4901, done.
remote: Counting objects: 100% (4901/4901), done.
remote: Compressing objects: 100% (4696/4696), done.
remote: Total 4901 (delta 50), reused 330 (delta 13), pack-reused 0
Receiving objects: 100% (4901/4901), 4.27 MiB | 1.57 MiB/s, done.
Resolving deltas: 100% (50/50), done.
Checking out files: 100% (4917/4917), done.
Error: Invalid formula: /home/chauveau/cadfaelbrew/Library/Taps/homebrew/homebrew-core/Formula/curl.rb
uninitialized constant Homebrew::DEFAULT_PREFIX
Error: Invalid formula: /home/chauveau/cadfaelbrew/Library/Taps/homebrew/homebrew-core/Formula/fontconfig.rb
uninitialized constant Homebrew::DEFAULT_PREFIX
Error: Invalid formula: /home/chauveau/cadfaelbrew/Library/Taps/homebrew/homebrew-core/Formula/gcc.rb
uninitialized constant Homebrew::DEFAULT_PREFIX
Error: Invalid formula: /home/chauveau/cadfaelbrew/Library/Taps/homebrew/homebrew-core/Formula/llvm@4.rb
uninitialized constant Homebrew::DEFAULT_PREFIX
Error: Invalid formula: /home/chauveau/cadfaelbrew/Library/Taps/homebrew/homebrew-core/Formula/llvm@5.rb
uninitialized constant Homebrew::DEFAULT_PREFIX

```

**Comment by emchauve** [comment]
some additionnal information:
```
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-ia32:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-ia32:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-ia32:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-ia32:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.5.1804 (Core) 
Release:	7.5.1804
Codename:	Core

emchauve@cca002:~ $ uname -a
Linux cca002 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

emchauve@cca002:~ $ cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core) 

emchauve@cca002:~ $ which gcc
/usr/bin/gcc

emchauve@cca002:~ $ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

emchauve@cca002:~ $ python --version
Python 2.7.5

emchauve@cca002:~ $ cvmfs_config probe
Probing /cvmfs/config-egi.egi.eu... OK
Probing /cvmfs/atlas.cern.ch... OK
Probing /cvmfs/atlas-condb.cern.ch... OK
Probing /cvmfs/lhcb.cern.ch... OK
Probing /cvmfs/cms.cern.ch... OK
Probing /cvmfs/alice.cern.ch... OK
Probing /cvmfs/alice-ocdb.cern.ch... OK
Probing /cvmfs/sft.cern.ch... OK
Probing /cvmfs/ams.cern.ch... OK
Probing /cvmfs/ilc.desy.de... OK
Probing /cvmfs/auger.egi.eu... OK
Probing /cvmfs/cta.in2p3.fr... OK
Probing /cvmfs/dirac.egi.eu... OK
Probing /cvmfs/km3net.egi.eu... OK
Probing /cvmfs/euclid.in2p3.fr... OK
Probing /cvmfs/oasis.opensciencegrid.org... OK
Probing /cvmfs/atlas-nightlies.cern.ch... OK
Probing /cvmfs/francegrilles.in2p3.fr... OK
Probing /cvmfs/euclid-dev.in2p3.fr... OK
Probing /cvmfs/ligo.osgstorage.org... Failed!
Probing /cvmfs/sw.lsst.eu... OK
Probing /cvmfs/singularity.opensciencegrid.org... OK
Probing /cvmfs/grid.cern.ch... OK
Probing /cvmfs/singularity.in2p3.fr... OK
Probing /cvmfs/glast.cern.ch... OK
Probing /cvmfs/xenon.opensciencegrid.org... OK
Probing /cvmfs/fermilab.opensciencegrid.org... OK
Probing /cvmfs/lhcb-condb.cern.ch... OK
Probing /cvmfs/ligo-containers.opensciencegrid.org... OK
Probing /cvmfs/larsoft.opensciencegrid.org... OK
Probing /cvmfs/dune.opensciencegrid.org... OK
```

**Comment by drbenmorgan** [comment]
Excellent, thanks @emchauve! As noted offline, the error is down to our fork of brew needing an update. Whilst I've looked at this, it's going to be a bit cleaner to fully migrate to use upstream linuxbrew. I've tested the following on our local CentOS7 system, so if you could try it at Lyon that should help find any issues related to the system rather than brew:

* Start from a fresh session
* Get official linuxbrew and set `PATH` plus env vars to check that formulae with be built from source and without advanced processor features
  ```
  $ git clone https://github.com/Linuxbrew/brew.git
  $ export PATH=$(pwd)/brew/bin:$PATH
  $ export HOMEBREW_BUILD_FROM_SOURCE=1
  $ export HOMEBREW_NO_AUTO_UPDATE=1
  $ export HOMEBREW_ARCH=core2
  ```
* Run the doctor command, which will likely complain but only about outdated `git` and that the build from source is set.
* Copy the following into a file named `Brewfile`:
  ```
  tap "homebrew/bundle"
  tap "homebrew/core"
  tap "linuxbrew/extra"
  tap "supernemo-dbd/cadfael", pin: true
  brew "gcc", args: ["without-glibc"]
  brew "fontconfig", args: ["without-docs"]
  brew "supernemo-dbd/cadfael/bayeux"
  brew "supernemo-dbd/cadfael/falaise"
  ```
* Running the following should try to install everything:
  ```
  $  brew bundle install -v --file=./Brewfile 
  ... lots of output ...
  ```

I can't guarantee that this will totally succeed, but let's see where it gets too. One place it *did* fail on my machine was with the `expat` formula, so it's possible that may do so here, but depends on exactly what rpms are installed. To guarantee that it doesn't, you can do

```
$ brew edit expat
```

and update the `def install` method to read:

```ruby
  def install
      system "./configure", "--prefix=#{prefix}",
                            "--mandir=#{man}",
                            "--without-docbook",
                            *("--with-libbsd" unless OS.mac?)
     system "make", "install"
   end
```

i.e., just adding the `--without-docbook` arg.

If the install fails along the way, just post here with which formula caused the issue, and the `config`, `doctor` and `gist-logs` as requested in https://github.com/SuperNEMO-DBD/homebrew-cadfael/blob/master/.github/ISSUE_TEMPLATE.md#bug-reports

**Comment by emchauve** [comment]
this is working in this way (having same failure with expat formula but fixed without docbook)

**Comment by drbenmorgan** [comment]
O.k., if you could just check that things can run with:

```console
$ brew test bayeux
$ brew test falaise
```

you should then be good to go. The same installation procedure can be used to create a common install under a directory of choice.

**Comment by emchauve** [comment]
test succeed

i notice 2 issues during installation :
- failure to download doxygen (https://downloads.sourceforge.net/project/doxygen/rel-1.8.12/doxygen-1.8.12.src.tar.gz) because of timeout (`curl: (28) Operation timed out after 5003 milliseconds with 0 out of 0 bytes received`).  it happened twice, the link is valid so i downloaded the file by hand. perhaps a temporary slow down of sourceforge servers. we could eventually increase the timeout from 5s to 10s ?
- during compilation of qt5-base, so the command bellow failed with "ld : cannot find -lmysqlclient" while /usr/lib64/mysql/libmysqlclient.so exist and is valid. i don't see why.. i made a symbolic link into brew/lib directory to fix it temporary
```
g++ -Wl,--no-undefined -Wl,-O1 -Wl,--enable-new-dtags -Wl,-z,origin -Wl,-rpath,\$ORIGIN/../../lib -Wl,-rpath,/u/chauveau/software/brew/Cellar/qt5-base/5.10.1/lib -Wl,-rpath,/u/chauveau/software/brew/lib -shared -o libqsqlmysql.so .obj/qsql_mysql.o .obj/main.o .obj/moc_qsql_mysql_p.o  -L/tmp/homebrew/qt5-base-20181010-6991-1fyouyx/qtbase-everywhere-src-5.10.1/lib -lQt5Sql -lQt5Core -lpthread -L/usr/lib64/mysql -lmysqlclient
```

**Comment by drbenmorgan** [comment]
Thanks, the first is unavoidable unfortunately, unless a faster mirror can be found.

For the second, I'll update the `qt5-base` formula to not pick up the system mysql.
