### ISSUE TITLE
Add xrootd support in ROOT Formula

### ISSUE THREAD

**Issue by drbenmorgan** [SuperNEMO-DBD/homebrew-cadfael#51]
### Formula Requests:

**Please note by far the quickest way to get a new formula into Linuxbrew is to file a [Pull Request](https://github.com/supernemo-dbd/homebrew-cadfael/blob/master/CONTRIBUTING.md).**

Per request from @emchauve, we need to add `xrootd` support in ROOT to access data. This will require:

- Update of `root6` formula to build `xrootd` support
- Provision of new formula `xrootd` (http://xrootd.org) with version sufficient/matched to server version which is currently `4.6.1`

Likely start with that version and upgrade as compatibility allows.

**Comment by drbenmorgan** [comment]
@emchauve, I have now provided an `xrootd` formula. Could you please try (at Lyon using the install you've just done):

```console
$ brew update
$ brew install xrootd
$ brew test xrootd
```

please, and report any errors here. Thanks!

**Comment by emchauve** [comment]
i will test it if i managed to get fresh install in Lyon (the recent install in on a CentOS7 machine was my lab!!)

so you added xrootd, and not just xrootd builtin support within ROOT ?

**Comment by drbenmorgan** [comment]
It's generally easier and cleaner to manage dependencies separately, and considered best practice (see [this talk](https://archive.fosdem.org/2018/schedule/event/how_to_make_package_managers_cry/) for example).

**Comment by emchauve** [comment]
ok i see ! :)  i will watch this talk later

**Comment by emchauve** [comment]
installation of xrootd succeeded, but something must be enabled in ROOT compilation in order to get the required library (lib/root/libNetx.so)

**Comment by drbenmorgan** [comment]
@emchauve, this should now work, but to enable it you'll need to do:

```console
$ brew update
$ brew reinstall root6
```

The resulting root install should have full xrootd support, plus install the actual xrootd command line programs. Let me know if anything is still missing.

**Comment by emchauve** [comment]
thanks, I did root6 reinstallation but without brew update before!
i can open now XROOTD file with our ROOT in Cadfael! :+1:

**Comment by emchauve** [comment]
opening is working fine with ROOT CINT, after loading Bayeux and Falaise libraries (to get definition of brio_record and TArrayCMod and datamodels)

```
root [0] 
root [0] .L $BX_INSTALL_PATH/lib64/libBayeux.so
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for inc/brio/detail/brio_record.h
   requested to autoload type TArrayCMod
Error in cling::AutoloadingVisitor::InsertIntoAutoloadingState:
   Missing FileEntry for inc/brio/detail/brio_record.h
   requested to autoload type brio_record
root [1] .L $FL_INSTALL_PATH/lib64/libFalaise.so
root [2] TFile::Open("root://ccxroot.in2p3.fr:1999//hpss/in2p3.fr/group/nemo/users/emchauve/test/test-se82-bb0n-raw.brio");
root [3] .ls
TNetXNGFile**		root://ccxroot.in2p3.fr:1999//hpss/in2p3.fr/group/nemo/users/emchauve/test/test-se82-bb0n-raw.brio	ROOT file from the `brio' library
 TNetXNGFile*		root://ccxroot.in2p3.fr:1999//hpss/in2p3.fr/group/nemo/users/emchauve/test/test-se82-bb0n-raw.brio	ROOT file from the `brio' library
  KEY: TTree	GI;1	GI tree for binary archive serialization
  KEY: TTree	ER;1	ER tree for binary archive serialization
root [4] GI->Show(0)
======> EVENT:0
 datatools::properties = (brio_record*)0x3ed8370
root [5] ER->Show(0)
======> EVENT:0
 datatools::things = (brio_record*)0x5c9b9a0
```

however flreconstruct does not digest the XROOTD address:

```
$ flreconstruct -i root://ccxroot.in2p3.fr:1999//hpss/in2p3.fr/group/nemo/users/emchauve/test/test-se82-bb0n-raw.brio
terminate called after throwing an instance of 'std::logic_error'
  what():  [void FLReconstruct::do_postprocess(FLReconstruct::FLReconstructParams&):430: Missing services configuration file!]
Aborted
```

it looks flreconstruct is trying to extract some argument from the address.
